### ISSUE TITLE
nwpAccordion not rendering child fields

### ISSUE THREAD

**Issue by coxrichuk** [saburab/angular-schema-form-nwp-components#1]
I am trying to use `nwpAccordion` but the fields I am pass to `items` are not being rendered?

Do I need to pass in the field keys or the field object to `items`?

**Comment by saburab** [comment]
the accordion is very rudimentary. instead you should try to use a tab array in combination with a custom template (which should be integrated with the help of the provider). Im sorry, but we right now have no further time to go on with this components. You should use this just a kind of example how to build your own components. Thank you for writing and good luck.

**Comment by coxrichuk** [comment]
Okay thank you.
